kind: pipeline
type: docker
name: test-name

steps:
  - name: firstStep-adding
    image: node
    pull: always
    commands:
      - node index.js
      - ls
      - echo HelloWorld
trigger:
  branch:
    - master
  event:
    - push
    - pull_request

# kind: pipeline
# type: exec
# name: exec-pipeline
# platform:
#   os: linux
#   arch: arm
# steps:
#   - name: echo-USERss 
#     commands:
#       - echo hello-world
# trigger:
#   branch:
#     - master
#   event:
#     - push