# kind: pipeline
# type: docker
# name: test-name

# steps:
#   - name: firstStep
#     image: node-alpine
#     pull: always
#     commands:
#       - node index.js
#       - ls
# trigger:
#   branch:
#     - master
#   event:
#     - push

kind: pipeline
type: exec
name: exec-test
steps:
  - name: echo-host
    commands:
      - echo "USER: $USER hostname: $HOSTNAME"
